#!/bin/bash

set -euo pipefail
set -x

if ! [ $(id -u) == 0 ]; then
	echo must be run as root 1>&2
	exit 1
fi

# Delete all existing users except root (and firebird?? TODO what is this????)
grep -ve '^root' -e '^firebird' /etc/passwd | cut -d: -f1 | xargs -n 1 userdel -f -r

# Password hash corresponds to `password`
adduser seagloperator -c 'SeaGL Operator' -mp '$y$j9T$emVbho1jsDyzxlJVlATJU.$GYps0oI9FuW.WC3KCXZQkRDq8zGV0gjDIuJLAK1mtP8' -G wheel
mkdir /home/seagloperator/RawVideo
chown seagloperator:seagloperator /home/seagloperator/RawVideo

mkdir -p /var/lib/seagl-nextcloud
chown seagloperator:seagloperator /var/lib/seagl-nextcloud
systemctl try-restart home-seagloperator-Nextcloud.mount

touch /var/lib/seagl/users-created
